export const GET_ALL_PRODUCT_REQUEST="GET_ALL_PRODUCT_REQUEST";
export const SELECT_ALL_PRODUCT="SELECT_ALL_PRODUCT";
export const SELECTED_PRODUCT="SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT="REMOVE_SELECTED_PRODUCT";